### ISSUE TITLE
Allow to communicate sleep time

### ISSUE THREAD

**Issue by agners** [home-assistant/bthome.io#10]
Home Assistant currently assumes to receive an update every 5 minutes. If a sensor updates less often, the state of the sensor changes to unavailable.

Sensors might have widely different sleep times. Instead of making assumptions, it would be nice to have an option to communicate the expected sleep time using the BTHome protocol.

Related issue: https://github.com/home-assistant/core/issues/78702

**Comment by balloob** [comment]
Since there is more information we might want to communicate, I suggest an approach like #11 to include message interval.

**Comment by Ernst79** [comment]
This issue should be fixed with https://github.com/home-assistant/core/pull/79669 This PR will make HA automatically determine the update interval, so there shouldn't be a need to communicate the sleep time anymore.
