### ISSUE TITLE
Characteristic to offer configuration

### ISSUE THREAD

**Issue by balloob** [home-assistant/bthome.io#11]
Some data we want the receiver to know but it never changes. It would be nice if we could offer a read-only characteristic for receivers to fetch this. It could contain:

 - Device class
 - Interval that data is send (for unavailable tracking)
 - Extended name
 - Firmware name
 - Firmware version
 - Model name
 - Manufacturer name

The flow would be:
 - Receiver sees a BTHome packet
 - Receiver makes a connection to fetch the static configuration
 - Receiver will from time to time refresh the static configuration

**Comment by bdraco** [comment]
We could also interleave the advertisements to send this hourly and on first boot so we don't have to make a connection very often.  Once it does makes a connection it never has to do it again.. or not at all if it saw it boot (also would handle passive only ones).

**Comment by Ernst79** [comment]
It would save some bytes from the advertisements, as as one doesn't have to include the name anymore. 

However, wouldn't this change force a sensor device to keep it awake all the time? It needs to be able to receive a request for its characteristics, so it can't go into a deep sleep, like the b-parisite sensors do, if I remember correct @rbaron

**Comment by Ernst79** [comment]
Maybe a different idea, if we include 2 bytes `device_flag`, we can add the above device characteristics in the code directly. This would add two bytes, but it saves al least 3 bytes of the name advertisement (len byte + name flag (0x09) + the actual name). Moreover, it would remove the need to make an active connection. 

The only downside I see is that a user has to make a request to have its device_flag added to the code. But we can allow the old way as well (without device_flag, but with name). 

e.g. 

```python
device_flag= "0x34AB" --> {
    "name": "b-parisite",
    "model": "plant sensor v1",
    "manufacturer": "rbaron",
    "firmware": "b-parasite firmware",
    "firmware version": "2.0",
    "broadcasting_interval": 600,
}
```

**Comment by balloob** [comment]
I guess bdraco's idea of transmitting device info once an hour works too. It's just a bid annoying because Home Assistant will need to allocate the device and it won't know the name.

**Comment by Ernst79** [comment]
That is why I propose to add a 2 byte `device_flag` in each message. In that way, each message has the device info (which we store in bthome-ble pypi package) linked to the `device_flag` bytes (2 bytes). 

No need to send the name info anymore than, so in the end it would safe bytes, and we can define all the info in the bthome-ble parser pypi package we want.

Xiaomi does the same, they also have a 2 byte device identifier in the payload.

**Comment by Ernst79** [comment]
As discussed on discord, we abandoned the idea of a `device_flag` with 2 bytes that identify predefined devices and will define a `device_info_available flag` to tell that device information is available as GATT characteristic. The (yet to be defined) GATT characteristic(s) holds device information and (if safely possible) the 16 byte encryption key.

Example is the pvvx ATC firmware, that also holds device info and keys, that can be read after connecting to the device
https://github.com/pvvx/ATC_MiThermometer#control-function-id-when-connected

**Comment by Ernst79** [comment]
Moved the issue to the Bluetooth-Devices/bthome-ble repo. https://github.com/Bluetooth-Devices/bthome-ble/issues/25
