### ISSUE TITLE
New BTHome Project

### ISSUE THREAD

**Issue by stumpylog** [home-assistant/bthome.io#13]
I'm not sure if there's requirements or anything for a mention, but I've written a project using the ESP-IDF tools to send BTHome format packets, which some people may find useful to make their own sensor packages.

https://github.com/stumpylog/bthome-weather-station

**Comment by balloob** [comment]
That's great. Would you want to open a PR to our readme to add your project?

**Comment by stumpylog** [comment]
Thanks, I wasn't sure if there needed to be any thing special to get a mention.  Always feels a little weird to self promote!
