### ISSUE TITLE
bthome and android mac address randomization

### ISSUE THREAD

**Issue by Sorien** [home-assistant/bthome.io#16]
I'm trying to create presence detection based on sending packets with presence data from my phone every 60 seconds, that part working fine but android randomizes the mac address every few minutes so when I come home from a walk home assistant detects my phone as new device cause of that mac address change, there is no way how to set static mac address in android, 

is there any way how to overcome this?

maybe you could add some new data type like a unique mac address...

**Comment by Ernst79** [comment]
Problem is that Home Assistant is using the MAC address as `address`, which is used in the unique id. And phones (both apple and android) use a rotating MAC address for privacy reasons, which is already found out. 

It should be possible to create a workaround, similar as for the iBeacon devices, which also have a rotating MAC address. iBeacon devices use an uuid inside the payload, which can be used as unique id. We can check how @bdraco did this for the iBeacon integration, but I'm afraid this is not going to be be an easy change.

**Comment by Sorien** [comment]
at first i thought that iBeacon will have similar problem but as you said it uses uuid not mac to identify device so i'll use iBeacon instead as it should solve my use case, once i get it working `https://github.com/home-assistant/core/issues/80357`

**Comment by Ernst79** [comment]
Ok, I'll close this issue than, as your use case is solved.
