### ISSUE TITLE
sensor update only once

### ISSUE THREAD

**Issue by 50494554524F** [home-assistant/bthome.io#35]
i'm using the pvvx firmware with a xiaomi thermometer 2 and i see the voltage sensor updating only one time after homeassistant startup.

bug or we have a big update interval to wait?!

(temperature or humidity update as expected)

thanks

**Comment by 50494554524F** [comment]
no, it updates every 30 minutes (seems)... it was a coincidence the update on startup

bthome or pvvx?!

**Comment by Ernst79** [comment]
Not sure why, the update interval of pvvx firmware should be multiple times per minute, when using default settings. In HA, you probably only see an update is the temperature changes. Assuming it has changed more often in these 30 minutes, its probably bad reception, low battery of USB3 devices/Wifi interference with your Bluetooth radio. You can find some tips here 
https://custom-components.github.io/ble_monitor/faq#reception-issues

**Comment by 50494554524F** [comment]
i tried swapping two batteries: once the battery is inserted sensors update as expected but the voltage and the one called power (i don't know what it is)...

going to ask to pvvx too...

**Comment by 50494554524F** [comment]
ok guys, found the problem... when i use suspension for my developing pc the frontend doesn't update the relative time shown on video or it can happen the value updates and revert back... i was watching "live", i don't know why

sorry, you can delete mt post...
