### ISSUE TITLE
ShellyBLU button 1 empty log

### ISSUE THREAD

**Issue by jeroenvdd** [home-assistant/bthome.io#39]
Hey,
I don't know if this is a bug of the bthome integration or something on the HA side,
but the shellyBLU button1 works fine if you use automations,
but the button itself isn't seen as a switch / entity

so no actions show up in the log aswell when pressing the button,
only the battery gets updated etc

**Comment by Ernst79** [comment]
The BLU button is sending button events + battery sensor. So, you only get events in Home Assistant, and a battery sensor, like you are saying. 

Adding binary sensor entities to Home Assistant will be difficult, as it will require not one entity, but 6 entities. One for short press, one for long press, and each for single, double or triple click. Anyway, you should be able to achieve whatever you want, with an automation. You could attach an events to a binary sensor and update it based on events. 

I will look into actions showing up in the device logbook.

**Comment by jeroenvdd** [comment]
thx for this, even an extra enitity 'last communication' wouldn't be to bad too :)
especially for the future. (when beacon mode is no longer beta)
cause now when my device is in beacon i need to check battery updated with some shenanigan's to find out if the button is 'home'

**Comment by Ernst79** [comment]
Note to myself: we have to add a logbook platform to HA to make the events visible in the logbook

Example: https://github.com/home-assistant/core/blob/dev/homeassistant/components/shelly/logbook.py

**Comment by Ernst79** [comment]
I think we can close this issue, the logbook has been added to HA
