### ISSUE TITLE
Allow types to be specified multiple times

### ISSUE THREAD

**Issue by balloob** [home-assistant/bthome.io#7]
We want to allow a device to be able to report multiple measurements of the same data type. For example, a BBQ thermometer wants to report 4 temperature sensors.

- Allow the payload to support specifying the same data type multiple times
- Receiver will need to append numbers after the name for a type if a payload contains multiple of that type, ie temperature 1, temperature 2
- The data type that is specified multiple times will always need to be grouped together in the same payload and in the same order for the receiver to be able to find it. There is no index field.

**Comment by Ernst79** [comment]
Added a PR to support multiple measurements of the same type. It will use the `device_id` field with `1, 2` etc if multiple measurements of the same type are present. if only one measurement per type is present, it will use `device_id = None`, as before.

**Comment by Ernst79** [comment]
This has been added to both V1 and V2, and has been merged.
