### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by balloob** [home-assistant/bthome.io#9]
Home Assistant has the [notion of tags](https://www.home-assistant.io/blog/2020/09/15/home-assistant-tags/). A tag is a random string that can be used for automations. It would be great if tag readers could be supported by BTHome to be able to support battery-powered tag readers.

- Add a new data type `tag` whose data is a string. Tags do not have a fixed length in Home Assistant.

Receiver should process it as a tag if it supports tags. In Home Assistant that will be [`async_scan_tag`](https://github.com/home-assistant/core/blob/dev/homeassistant/components/tag/__init__.py#L110) if the `tag` integration is set up.

**Comment by Ernst79** [comment]
Moving all issues to the Bluetooth-Devices/BTHome repo. 

This issues has been moved to https://github.com/Bluetooth-Devices/bthome-ble/issues/24
